apiVersion: v1
entries:
  systems-information:
  - apiVersion: v1
    appVersion: 0.0.1-rc3
    created: "2020-06-23T00:07:10.362962889-05:00"
    description: Rancher Systems Summary Report
    digest: 993b910f4bfa0e701b9d673b395d53f366a1c185d1c718928c3e0bb7be699e25
    home: https://support.rancher.com
    icon: https://rancher.com/img/brand-guidelines/assets/logos/png/color/rancher-logo-stacked-color.png
    keywords:
    - rancher
    - support
    maintainers:
    - email: Matthew.Mattox@rancher.com
      name: mattmattox
    name: systems-information
    sources:
    - https://github.com/rancherlabs/support-tools
    type: application
    urls:
    - https://rancherlabs.github.io/support-tools/charts/systems-information-0.0.1-rc3.tgz
    version: 0.0.1-rc3
  - apiVersion: v2
    appVersion: 0.0.1-rc2
    created: "2020-06-23T00:07:10.361476046-05:00"
    description: Rancher Systems Summary Report
    digest: 1dfc0b79dfa1dcb727fdf8acad364df0be99ce5e8184c7c28ad30369903c0bc3
    home: support.rancher.com
    icon: https://rancher.com/img/brand-guidelines/assets/logos/png/color/rancher-logo-stacked-color.png
    keywords:
    - rancher
    - support
    maintainers:
    - email: Matthew.Mattox@rancher.com
      name: mattmattox
    name: systems-information
    sources:
    - https://github.com/rancherlabs/support-tools
    type: application
    urls:
    - https://rancherlabs.github.io/support-tools/charts/systems-information-0.0.1-rc2.tgz
    version: 0.0.1-rc2
  - apiVersion: v2
    appVersion: 0.0.1-rc1
    created: "2020-06-23T00:07:10.359614207-05:00"
    description: Rancher Systems Summary Report
    digest: 038a060e89eec1ede7ec96f0012ed61e8217e0d9c75f529a9d1436e5640d615d
    home: support.rancher.com
    icon: https://rancher.com/img/brand-guidelines/assets/logos/png/color/rancher-logo-stacked-color.png
    keywords:
    - rancher
    - support
    maintainers:
    - email: Matthew.Mattox@rancher.com
      name: mattmattox
    name: systems-information
    sources:
    - https://github.com/rancherlabs/support-tools
    type: application
    urls:
    - https://rancherlabs.github.io/support-tools/charts/systems-information-0.0.1-rc1.tgz
    version: 0.0.1-rc1
generated: "2020-06-23T00:07:10.358757938-05:00"
